cmd is now single argument; rest is list of ioc-names (cmdOnIOCs)

diff --git a/bin/cmdOnIOCs b/bin/cmdOnIOCs
--- a/bin/cmdOnIOCs
+++ b/bin/cmdOnIOCs
@@ -1,8 +1,8 @@
 #!/usr/bin/zsh -f
 
-if [[ "$*" = "" ]]; then
+usage() {
 <<EOF
-Usage: $(basename "$0") [-n] [-f] [-s seconds] [-e escape] -p passwd (-i iocsglob|-I iocsregex) cmd
+Usage: cmdOnIOCs [-n] [-f] [-s seconds] [-e escape] -p passwd (-i iocsglob|-I iocsregex) cmd [iocs]
 
   -n          : no-exec - just print what would be executed without giving "-n"
   -f          : force   - skip the "do you really..." part, just do it
@@ -12,12 +12,15 @@ Usage: $(basename "$0") [-n] [-f] [-s seconds] [-e escape] -p passwd (-i iocsglo
   -p passwd   : passwd  - console-password to access ioc
   -i glob     : iocs    - space separated list of glob-patterns matching ioc-names
   -I regex    : iocs    - space separated list of regexps matching ioc-names
-  cmd         : command - the actual command to execute on each matching ioc
+  cmd         : command - the actual command to execute on each matching ioc (single argument!)
+  iocs        : iocs    - simple list of iocnames (overrides -i and -I!)
 
 A simple list of space-separated IOC-names is perfectly OK for both -i and -I...
 EOF
-  exit 0
-fi
+
+  exit $1
+}
+[[ "$*" = "" ]] && usage 0
 
 zparseopts -D -A args -- I: i: s: e: p: f n
 
@@ -30,34 +33,36 @@ sleep=${args[-s]-1}
 password=${args[-p]-xxx}
 esc=${args[-e]-XX}
 
-if [[ $iocsre != "xxx" && $iocsglob != "xxx" ]]; then
-  echo "ERROR: Only one of \"-i iocsglob\" and \"-I iocsregex\" can be given." >&2
-  exit 1
-fi
-if [[ $iocsre = "xxx" && $iocsglob = "xxx" ]]; then
-  echo "ERROR: One of \"-i iocsglob\" and \"-I iocsregex\" has to be given." >&2
-  exit 1
+cmd=$1; shift
+
+if [[ $# == 0 && $iocsre = "xxx" && $iocsglob = "xxx" ]]; then
+  echo "ERROR: No IOCs specified.\n" >&2
+  usage 1
 fi
 if [[ $password = "xxx" ]]; then
-  echo "ERROR: Password has to be provided!" >&2
-  exit 1
+  echo "ERROR: Password has to be provided!\n" >&2
+  usage 1
 fi
 
 [[ $iocsre = "xxx" ]] && iocsre=".*" && iocsglob=${(j:|:)${=iocsglob}}
 [[ $iocsglob = "xxx" ]] && iocsglob="*" && iocsre=${(j:|:)${=iocsre}}
 
-iocs=()
-foreach ioc (`echo tsc | console -u 2>/dev/null |awk '{print $1}' | sort | egrep ^\($iocsre\)$`)
-  [[ "$ioc" = ${~iocsglob} ]] && iocs=($iocs $ioc)
-end
+if [[ $# > 0 ]]; then
+  iocs=("$@")
+else
+  iocs=()
+  foreach ioc (`echo tsc | console -u 2>/dev/null |awk '{print $1}' | sort | egrep ^\($iocsre\)$`)
+    [[ "$ioc" = ${~iocsglob} ]] && iocs=($iocs $ioc)
+  end
+fi
 
 if [[ $#iocs = 0 ]]; then
-  echo "ERROR: No matching IOCs found" >&2
-  exit 1
+  echo "ERROR: No matching IOCs found\n" >&2
+  usage 1
 fi
 
 if [[ $noexec == 0 && $force == 0 ]]; then
-  echo -n "Execute command\n\t$@\non IOCs\n\t$iocs\n\nIs that what you really want? (y/N)"
+  echo -n "Execute command\n\t$cmd\non IOCs\n\t$iocs\n\nIs that what you really want? (y/N)"
   read ans
   [[ $ans:u != "Y" ]] && exit 0
 fi
@@ -65,9 +70,9 @@ fi
 foreach ioc ($iocs)
   if [[ $noexec == 1 ]]; then
 <<EOF
-    (echo "$password"; sleep 1; echo $@; sleep $sleep; echo "${esc}.") | console -e "$esc" $ioc;
+    (echo "$password"; sleep 1; echo $cmd; sleep $sleep; echo "${esc}.") | console -e "$esc" $ioc;
 EOF
   else
-    (echo "$password"; sleep 1; echo $@; sleep $sleep; echo "${esc}.") | console -e "$esc" $ioc;
+    (echo "$password"; sleep 1; echo $cmd; sleep $sleep; echo "${esc}.") | console -e "$esc" $ioc;
   fi
 end
