improvements in cmdOnIOCs

diff --git a/bin/cmdOnIOCs b/bin/cmdOnIOCs
--- a/bin/cmdOnIOCs
+++ b/bin/cmdOnIOCs
@@ -18,7 +18,7 @@ Usage: cmdOnIOCs [-n] [-f] [-s seconds] [-e escape] -p passwd (-i iocsglob|-I io
 A simple list of space-separated IOC-names is perfectly OK for both -i and -I...
 EOF
 
-  exit $1
+   exit $1
 }
 [[ "$*" = "" ]] && usage 0
 
@@ -36,43 +36,52 @@ esc=${args[-e]-XX}
 cmd=$1; shift
 
 if [[ $# == 0 && $iocsre = "xxx" && $iocsglob = "xxx" ]]; then
-  echo "ERROR: No IOCs specified.\n" >&2
-  usage 1
+    echo "ERROR: No IOCs specified.\n" >&2
+    usage 1
 fi
 if [[ $password = "xxx" ]]; then
-  echo "ERROR: Password has to be provided!\n" >&2
-  usage 1
+    echo "ERROR: Password has to be provided!\n" >&2
+    usage 1
 fi
 
 [[ $iocsre = "xxx" ]] && iocsre=".*" && iocsglob=${(j:|:)${=iocsglob}}
 [[ $iocsglob = "xxx" ]] && iocsglob="*" && iocsre=${(j:|:)${=iocsre}}
 
 if [[ $# > 0 ]]; then
-  iocs=("$@")
+    iocs=("$@")
 else
-  iocs=()
-  foreach ioc (`echo tsc | console -u 2>/dev/null |awk '{print $1}' | sort | egrep ^\($iocsre\)$`)
+    iocs=()
+    foreach ioc (`echo tsc | console -u 2>/dev/null |awk '{print $1}' | sort | egrep ^\($iocsre\)$`)
     [[ "$ioc" = ${~iocsglob} ]] && iocs=($iocs $ioc)
-  end
+    end
 fi
 
 if [[ $#iocs = 0 ]]; then
-  echo "ERROR: No matching IOCs found\n" >&2
-  usage 1
+    echo "ERROR: No matching IOCs found\n" >&2
+    usage 1
 fi
 
 if [[ $noexec == 0 && $force == 0 ]]; then
-  echo -n "Execute command\n\t$cmd\non IOCs\n\t$iocs\n\nIs that what you really want? (y/N)"
-  read ans
-  [[ $ans:u != "Y" ]] && exit 0
+    numiocs=$#iocs
+    if [[ numiocs -gt 1 ]]
+    then
+        echo "Execute command\n\t$cmd\non the following $numiocs IOCs:"
+        print -oc $iocs
+        echo -n "\nIs that what you really want? (y/N) "
+    else
+        echo -n "Execute command\n\t$cmd\non IOC $iocs\n\nIs that what you really want? (y/N) "
+    fi
+    read ans
+    [[ $ans:u != "Y" ]] && exit 0
 fi
 
-foreach ioc ($iocs)
-  if [[ $noexec == 1 ]]; then
-<<EOF
-    (echo "$password"; sleep 1; echo $cmd; sleep $sleep; echo "${esc}.") | console -f -e "$esc" $ioc;
+for ioc in $iocs
+do
+    if [[ $noexec == 1 ]]; then
+        <<EOF
+(echo "$password"; sleep 1; echo $cmd:q; sleep $sleep; echo "${esc}.") | console -f -e "$esc" $ioc;
 EOF
-  else
-    (echo "$password"; sleep 1; echo $cmd; sleep $sleep; echo "${esc}.") | console -f -e "$esc" $ioc;
-  fi
-end
+    else
+        (echo "$password"; sleep 1; echo $cmd; sleep $sleep; echo "${esc}.") | console -f -e "$esc" $ioc;
+    fi
+done
