idcp-dist-info now uses the iddb script.
By this change we no longer have insertion device properties hardcoded in this
script.

diff --git a/bin/idcp-dist-info b/bin/idcp-dist-info
--- a/bin/idcp-dist-info
+++ b/bin/idcp-dist-info
@@ -25,11 +25,6 @@ CONFIGFILE_MLS=$CONFIGFILE_PATH/rsync-dist.config.MLS
 
 CONFIGFILE=$CONFIGFILE_BII
 
-installed_ids_bii="^idcp(3|5|6|7|8|9|10|11|12|121|13|15|110|120)$"
-installed_ids_mls="^idcp(90)$"
-
-installed_ids=$installed_ids_bii
-
 function print_short_help {
     echo "$0: a small wrapper that calls rsync-dist-info.py"
     echo "options:"
@@ -40,7 +35,7 @@ function print_short_help {
     echo "      the rsync-dist.pl (Ue56/2 is not in this list)"
     echo "  --id-list : show the known insertion devices and their idcp-name"
     echo "  --facility [FACILITY]: set the facility, facility may"
-    echo "      be 'bii' or 'mls'"
+    echo "      be 'bii' (default) or 'mls'"
     echo "  --dry-run : just show how rsync-dist-info.py would be called"
 }
 
@@ -53,52 +48,13 @@ function print_long_help {
     rsync-dist-info.py -h
 }
 
-# declare all known insertion devices in a hash:
-
-IDs='U125-1:90\n
-U125/1:90\n
-U125-2:3\n
-U125/2:3\n
-U125ID2R:3\n
-U125IL2RP:90\n
-U139:110\n
-U139ID6R:110\n
-U17:120\n
-U17IT6R:120\n
-U41:6\n
-U41IT3R:6\n
-U49-1:7\n
-U49/1:7\n
-U49-2:15\n
-U49/2:15\n
-U49ID4R:7\n
-U49ID8R:15\n
-UE112:13\n
-UE112ID7R:13\n
-UE46:10\n
-UE46IT5R:10\n
-UE48:12\n
-UE48IT6R:12\n
-UE49:8\n
-UE49IT4R:8\n
-UE52:9\n
-UE52ID5R:9\n
-UE54:121\n
-UE54IT6R:121\n
-UE56-1:11\n
-UE56/1:11\n
-UE56-2:5\n
-UE56/2:5\n
-UE56ID3R:5\n
-UE56ID6R:11\n
-'
-
 function list_ids {
-    tags=`echo "$IDs" | sed -e 's/\([^:]\+\):\([^:]\+\):\([^:]\+\)/\\t\1\\t: \2/g'`
-    echo -e "$tags" | expand -t 10
+    iddb -a idcp
     exit 0
 }
 
+facility="bii"
+dryrun=""
 realargs="$@"
 while [ $# -gt 0 ]; do
     case "$1" in
@@ -111,17 +67,16 @@ while [ $# -gt 0 ]; do
         exit 0
         ;;
       --id-list)
-        list_ids
+        iddb -a idcp
         exit 0
         ;;
       --id)
-        no=`echo -e "$IDs" | egrep "^$2:"`
-        no=`echo $no | sed -e 's/^[^:]\+://g'`
-        if [[ -z "$no" ]]; then
-            echo "unknown ID:$2"
+        prefix=$(iddb prefix "$2" 2>/dev/null)
+        if [ $? -ne 0 ]; then
+            echo "unknown ID:$2 ('iddb $2' returned an error)"
             exit 1
         fi
-        opts="$opts --filter-names idcp$no"
+        opts="$opts --filter-names $prefix"
         shift
         ;;
       --idcp)
@@ -130,7 +85,6 @@ while [ $# -gt 0 ]; do
         ;;
       --ids)
         ids_par_given="yes"
-        opts="$opts --filter-names-rx $installed_ids"
         ;;
       -n| --names| -v| --versions| -l| --lifetimes| --idle| --boot-times| --version-info)
         saveme="$saveme $1"
@@ -149,12 +103,12 @@ while [ $# -gt 0 ]; do
         if [ "$2" = "mls" ]; then
             facility="$2"
             CONFIGFILE=$CONFIGFILE_MLS
-            installed_ids=$installed_ids_mls
         fi
         if [ "$facility" = "no" ]; then
             echo "unknown faciliy: $2"
             exit 1
         fi
+        shift
         ;;
       --dry-run)
         dryrun="yes"
@@ -168,7 +122,10 @@ while [ $# -gt 0 ]; do
 done
 
 if [[ -n "$ids_par_given" ]]; then
-    opts="$opts --filter-names-rx $installed_ids"
+    # facility in upper-case:
+    fct=${facility^^} 
+    installed_ids=$(iddb -a idcp -g $fct -s installed list prefix --no-heading | xargs | sed -e 's/ /,/g')
+    opts="$opts --filter-names $installed_ids"
 fi
 
 opts="$opts -c $CONFIGFILE"
