idcp-restore: Allow giving rsync-dist config file on the command line.

diff --git a/bin/idcp-restore b/bin/idcp-restore
--- a/bin/idcp-restore
+++ b/bin/idcp-restore
@@ -30,6 +30,8 @@ ID_DB_CENTRALREPO="http://repo.acc.bessy.de/hg/id_db"
 verbose=""
 dryrun=""
 
+configfile=""
+
 # "" stands for "bii", the default
 facility="bii"
 
@@ -71,15 +73,23 @@ function print_short_help {
     echo "VERSION:"
     echo "  The ISO date string as it is used by rsync-dist. "
     echo "OPTIONS:"
-    echo "  -h --help  : this help"
-    echo "  --dir DIR : Create source tree in directory DIR. Otherwise a"
-    echo "              directory name is created from the VERSION string"
-    echo "              in the form YYYY-MM-DDTHHMMSS."
-    echo "  -f --facility [FACILITY]: define facility, currently known:"
-    echo "        bii      : BESSY storage ring, the default"
-    echo "        mls      : MLS storage ring"
-    echo "  --verbose : show executed command"
-    echo "  --dry-run : just show how rsync-dist-info.py would be called"
+    echo "  -h --help :"
+    echo "      this help"
+    echo "  --dir DIR :"
+    echo "    Create source tree in directory DIR. Otherwise a"
+    echo "    directory name is created from the VERSION string"
+    echo "    in the form YYYY-MM-DDTHHMMSS."
+    echo "  -f --facility FACILITY :"
+    echo "    define facility, currently known:"
+    echo "      bii      : BESSY storage ring, the default"
+    echo "      mls      : MLS storage ring"
+    echo "  -c --config CONFIGFILE :"
+    echo "    Specify the rsync-dist configuration file to use. If this "
+    echo "    option is not givem, take the one from bii_scripts."
+    echo "  -v --verbose :"
+    echo "    show what the script does"
+    echo "  -n --dry-run :"
+    echo "    just show what the script would do"
 }
 
 declare -a ARGS
@@ -109,11 +119,16 @@ while true; do
                 fi
             done
             ;;
-        --verbose)
+        -c | --config)
+            configfile="$2"
+            shift 2
+            ;;
+        -v | --verbose)
             verbose="yes"
             shift
             ;;
         -n | --dry-run)
+            verbose="yes"
             dryrun="yes"
             shift
             ;;
@@ -146,21 +161,22 @@ if [ -n "$skip_options" ]; then
     done
 fi
 
-# read bii_scripts configuration variables:
-source $MYDIR/bii_scripts.config
-if [ $? -ne 0 ]; then
-    echo "error, file bii_scripts.config not found" >&2
-    exit
+if [ -z "$configfile" ]; then
+    # Take rsync-dist config file from bii_scripts share directory.
+    # read bii_scripts configuration variables:
+    source $MYDIR/bii_scripts.config
+    if [ $? -ne 0 ]; then
+        echo "error, file bii_scripts.config not found" >&2
+        exit
+    fi
+    # The share directory is defined by SHARE_INSTALL_DIR in file 
+    # bii_scripts.config:
+    CONFIGFILE_PATH=$SHARE_INSTALL_DIR/bii_scripts/rsync-dist 
+    configfile="$CONFIGFILE_PATH/idcp-$facility"
 fi
 
-# The share directory is defined by SHARE_INSTALL_DIR from file 
-# bii_scripts.config:
-BII_SCRIPTS_SHARE_DIR="$SHARE_INSTALL_DIR"
-
-CONFIGFILE_PATH=$BII_SCRIPTS_SHARE_DIR/bii_scripts/rsync-dist 
-
-configfile="$CONFIGFILE_PATH/idcp-$facility"
-
+# Source rsync-dist configuration file, this defines various variables, all
+# named RSYNC_DIST*
 source $configfile
 if [ $? -ne 0 ]; then
     echo "error, couldn't read $configfile" >&2
@@ -193,8 +209,6 @@ CMD "mkdir $MYVERSION"
 CD "$MYVERSION"
 
 echo -e "* fetching hg recover files from boot directory...\n"
-
-
 
 CMD "scp $RSYNC_DIST_USER@$RSYNC_DIST_HOST:$RSYNC_DIST_PATH/$QVERSION/dbd/hg-recover* ."
 if [ $cmdret -ne 0 ]; then 
